const actionTypes = {

    GET_CATALOG: 'GET_CATALOG',
    ALERT: 'ALERT',
    LOGIN: 'LOGIN',
    ACTION_WISHLIST: 'ACTION_WISHLIST',
    SHOW_CART: 'SHOW_CART',
    UPDATE_CURRENT: 'UPDATE_CURRENT',
    CART: 'CART',
    LOADING: 'LOADING',
    ADMIN: 'ADMIN',
    LOGOUT: 'LOGOUT',
    CAL_PRICE: 'CAL_PRICE',
    REMOVE_PRODUCT: 'REMOVE_PRODUCT',
    UPDATE_PRICE: 'UPDATE_PRICE',
    GET_BRAND: 'GET_BRAND',
    SET_CART: 'SET_CART',
    SKU: 'SKU',
    RESET_ORDER: 'RESET_ORDER',
    DEL_ORDER: 'DEL_ORDER'

}

export default actionTypes